GET http://localhost:3000/6waGO5p5y
###

GET http://localhost:3000/
###

POST http://localhost:3000
Content-Type: application/json

{
  "name": "This book",
  "author": "Author"
}
###
DELETE http://localhost:3000/6waGO5p5y